export {
  ALBATROSS_AUTH_TIMEOUT_SECONDS,
  ALBATROSS_COMPATIBILITY_PROFILE,
  ALBATROSS_CONTINUITY_GUIDANCE,
  ALBATROSS_MCP_REMOTE_VERSION,
  ALBATROSS_OAUTH_CLIENT_METADATA,
  ALBATROSS_PARTICIPANT_HEADER,
  ALBATROSS_PROFILE_PROMPT,
  ALBATROSS_PROFILE_RESOURCE_URI,
  ALBATROSS_WAIT_TIMEOUT_SECONDS,
  ALBATROSS_WORKSPACE_PROMPT,
  createAlbatrossAuthorizationCommand,
  createAlbatrossMcpMergeConfig,
  createAlbatrossSetupKit,
  serializeAlbatrossCompatibilityProfile,
  type OwdAlbatrossCompatibilityProfile,
} from "./albatross";
export {
  EVE_COMPATIBILITY_PROFILE,
  EVE_CONNECTION_DESCRIPTION,
  EVE_CONNECTION_INSTRUCTIONS,
  EVE_CONTINUITY_GUIDANCE,
  EVE_PROFILE_PROMPT,
  EVE_PROFILE_RESOURCE_URI,
  createEveConnectionSource,
  serializeEveCompatibilityProfile,
  type OwdEveCompatibilityProfile,
} from "./eve";
export {
  OBSIDIAN_MIND_COMPATIBILITY_PROFILE,
  OBSIDIAN_MIND_CONTINUITY_GUIDANCE,
  OBSIDIAN_MIND_PROFILE_PROMPT,
  OBSIDIAN_MIND_PROFILE_RESOURCE_URI,
  createObsidianMindMcpMergeConfig,
  createObsidianMindProjectMcpCommand,
  serializeObsidianMindCompatibilityProfile,
  type OwdVaultRuntimeCompatibilityProfile,
} from "./obsidian-mind";
