packages:
  - apps/*
  - packages/*

minimumReleaseAgeExclude:
  - eve@0.29.4

overrides:
  "@hono/node-server": 2.0.11
  sharp: 0.35.0

allowBuilds:
  core-js-pure: false
  esbuild: true
  sharp: true
  workerd: true
